#!/bin/bash

# IPv6 & Geolocation Disable Script for Linux
# Bash Script for Privacy and Network Configuration
# Author: XXMXLI Security Tools
# WARNING: Use only for legitimate purposes and with proper authorization

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Function to display banner
show_banner() {
    echo -e "${CYAN}"
    echo " ██╗██████╗ ██╗   ██╗ ██████╗      ██████╗ ███████╗ ██████╗ "
    echo " ██║██╔══██╗██║   ██║██╔════╝     ██╔════╝ ██╔════╝██╔═══██╗"
    echo " ██║██████╔╝██║   ██║███████╗     ██║  ███╗█████╗  ██║   ██║"
    echo " ██║██╔═══╝ ╚██╗ ██╔╝██╔═══██╗    ██║   ██║██╔══╝  ██║   ██║"
    echo " ██║██║      ╚████╔╝ ╚██████╔╝    ╚██████╔╝███████╗╚██████╔╝"
    echo " ╚═╝╚═╝       ╚═══╝   ╚═════╝      ╚═════╝ ╚══════╝ ╚═════╝ "
    echo ""
    echo "    IPv6 & Geolocation Disable Tool for Linux"
    echo "    Privacy Protection and Network Configuration"
    echo "    Educational and Authorized Use Only"
    echo -e "${NC}"
}

# Function to check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${RED}❌ This script must be run as root (use sudo)${NC}"
        echo -e "${YELLOW}Please run: sudo $0${NC}"
        exit 1
    fi
    echo -e "${GREEN}✅ Running with root privileges${NC}"
}

# Function to detect Linux distribution
detect_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$NAME
        VER=$VERSION_ID
    elif type lsb_release >/dev/null 2>&1; then
        OS=$(lsb_release -si)
        VER=$(lsb_release -sr)
    elif [ -f /etc/lsb-release ]; then
        . /etc/lsb-release
        OS=$DISTRIB_ID
        VER=$DISTRIB_RELEASE
    elif [ -f /etc/debian_version ]; then
        OS=Debian
        VER=$(cat /etc/debian_version)
    else
        OS=$(uname -s)
        VER=$(uname -r)
    fi
    
    echo -e "${CYAN}📋 Detected OS: $OS $VER${NC}"
}

# Function to backup current settings
backup_settings() {
    echo -e "${YELLOW}💾 Creating backup of current settings...${NC}"
    
    local timestamp=$(date +"%Y%m%d_%H%M%S")
    local backup_file="network_privacy_backup_${timestamp}.conf"
    
    {
        echo "# Network Privacy Settings Backup - $timestamp"
        echo "# Generated by XXMXLI IPv6 & Geolocation Disable Tool"
        echo ""
        
        echo "# IPv6 Status"
        echo "IPv6_PROC_DISABLE=$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null || echo 'unknown')"
        echo "IPv6_PROC_AUTOCONF=$(cat /proc/sys/net/ipv6/conf/all/autoconf 2>/dev/null || echo 'unknown')"
        echo "IPv6_PROC_ACCEPT_RA=$(cat /proc/sys/net/ipv6/conf/all/accept_ra 2>/dev/null || echo 'unknown')"
        
        echo ""
        echo "# Network Interfaces IPv6 Status"
        for interface in $(ls /sys/class/net/); do
            if [[ $interface != "lo" ]]; then
                echo "IPv6_${interface^^}_DISABLE=$(cat /proc/sys/net/ipv6/conf/$interface/disable_ipv6 2>/dev/null || echo 'unknown')"
            fi
        done
        
        echo ""
        echo "# Systemctl Services Status"
        systemctl is-enabled systemd-resolved 2>/dev/null && echo "SYSTEMD_RESOLVED_ENABLED=true" || echo "SYSTEMD_RESOLVED_ENABLED=false"
        systemctl is-enabled NetworkManager 2>/dev/null && echo "NETWORKMANAGER_ENABLED=true" || echo "NETWORKMANAGER_ENABLED=false"
        
        echo ""
        echo "# Geolocation Services (if any)"
        ps aux | grep -i "location\|geo" | grep -v grep | head -5
        
    } > "$backup_file"
    
    echo -e "${GREEN}✅ Backup saved to: $backup_file${NC}"
    echo -e "${CYAN}📁 Use this file to restore settings if needed${NC}"
}

# Function to disable IPv6
disable_ipv6() {
    echo -e "${YELLOW}🔄 Disabling IPv6...${NC}"
    
    # Method 1: Kernel parameters (immediate effect)
    echo -e "${CYAN}📝 Setting kernel parameters...${NC}"
    
    # Disable IPv6 for all interfaces
    echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
    echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
    
    # Disable IPv6 autoconfig
    echo 0 > /proc/sys/net/ipv6/conf/all/autoconf
    echo 0 > /proc/sys/net/ipv6/conf/default/autoconf
    
    # Disable IPv6 router advertisements
    echo 0 > /proc/sys/net/ipv6/conf/all/accept_ra
    echo 0 > /proc/sys/net/ipv6/conf/default/accept_ra
    
    # Disable IPv6 for specific interfaces
    for interface in $(ls /sys/class/net/); do
        if [[ $interface != "lo" ]]; then
            echo 1 > /proc/sys/net/ipv6/conf/$interface/disable_ipv6 2>/dev/null
            echo -e "  ✓ Disabled IPv6 on: $interface" -e "${GREEN}"
        fi
    done
    
    # Method 2: Persistent configuration via sysctl
    echo -e "${CYAN}📝 Creating persistent sysctl configuration...${NC}"
    
    cat > /etc/sysctl.d/99-disable-ipv6.conf << EOF
# Disable IPv6 - Generated by XXMXLI Privacy Tool
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.all.autoconf = 0
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
EOF
    
    # Apply sysctl settings
    sysctl -p /etc/sysctl.d/99-disable-ipv6.conf >/dev/null 2>&1
    
    # Method 3: GRUB configuration (requires reboot)
    echo -e "${CYAN}📝 Updating GRUB configuration...${NC}"
    
    if [ -f /etc/default/grub ]; then
        # Backup original grub file
        cp /etc/default/grub /etc/default/grub.backup.$(date +%Y%m%d_%H%M%S)
        
        # Add IPv6 disable parameter
        if grep -q "ipv6.disable=1" /etc/default/grub; then
            echo -e "  ✓ IPv6 disable parameter already present in GRUB"
        else
            sed -i 's/GRUB_CMDLINE_LINUX="/GRUB_CMDLINE_LINUX="ipv6.disable=1 /' /etc/default/grub
            echo -e "  ✓ Added IPv6 disable parameter to GRUB"
        fi
        
        # Update GRUB
        if command -v update-grub >/dev/null 2>&1; then
            update-grub >/dev/null 2>&1
        elif command -v grub2-mkconfig >/dev/null 2>&1; then
            grub2-mkconfig -o /boot/grub2/grub.cfg >/dev/null 2>&1
        elif command -v grub-mkconfig >/dev/null 2>&1; then
            grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1
        fi
        echo -e "  ✓ GRUB configuration updated"
    fi
    
    # Method 4: NetworkManager configuration (if present)
    if command -v nmcli >/dev/null 2>&1; then
        echo -e "${CYAN}📝 Configuring NetworkManager...${NC}"
        
        # Create NetworkManager configuration
        mkdir -p /etc/NetworkManager/conf.d/
        cat > /etc/NetworkManager/conf.d/99-disable-ipv6.conf << EOF
[connection]
ipv6.method=ignore
EOF
        
        # Restart NetworkManager if it's running
        if systemctl is-active NetworkManager >/dev/null 2>&1; then
            systemctl restart NetworkManager
            echo -e "  ✓ NetworkManager restarted with IPv6 disabled"
        fi
    fi
    
    echo -e "${GREEN}✅ IPv6 disabled successfully!${NC}"
    echo -e "${YELLOW}⚠️  A system reboot is recommended for full effect.${NC}"
}

# Function to enable IPv6
enable_ipv6() {
    echo -e "${YELLOW}🔄 Enabling IPv6...${NC}"
    
    # Enable IPv6 via kernel parameters
    echo -e "${CYAN}📝 Setting kernel parameters...${NC}"
    
    echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
    echo 0 > /proc/sys/net/ipv6/conf/default/disable_ipv6
    echo 1 > /proc/sys/net/ipv6/conf/all/autoconf
    echo 1 > /proc/sys/net/ipv6/conf/default/autoconf
    echo 1 > /proc/sys/net/ipv6/conf/all/accept_ra
    echo 1 > /proc/sys/net/ipv6/conf/default/accept_ra
    
    # Enable IPv6 for specific interfaces
    for interface in $(ls /sys/class/net/); do
        if [[ $interface != "lo" ]]; then
            echo 0 > /proc/sys/net/ipv6/conf/$interface/disable_ipv6 2>/dev/null
            echo -e "  ✓ Enabled IPv6 on: $interface"
        fi
    done
    
    # Remove persistent configuration
    echo -e "${CYAN}📝 Removing persistent sysctl configuration...${NC}"
    rm -f /etc/sysctl.d/99-disable-ipv6.conf
    
    # Remove GRUB parameter
    echo -e "${CYAN}📝 Updating GRUB configuration...${NC}"
    if [ -f /etc/default/grub ]; then
        sed -i 's/ipv6.disable=1 //g' /etc/default/grub
        
        # Update GRUB
        if command -v update-grub >/dev/null 2>&1; then
            update-grub >/dev/null 2>&1
        elif command -v grub2-mkconfig >/dev/null 2>&1; then
            grub2-mkconfig -o /boot/grub2/grub.cfg >/dev/null 2>&1
        elif command -v grub-mkconfig >/dev/null 2>&1; then
            grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1
        fi
        echo -e "  ✓ GRUB configuration updated"
    fi
    
    # Remove NetworkManager configuration
    rm -f /etc/NetworkManager/conf.d/99-disable-ipv6.conf
    
    if systemctl is-active NetworkManager >/dev/null 2>&1; then
        systemctl restart NetworkManager
        echo -e "  ✓ NetworkManager restarted with IPv6 enabled"
    fi
    
    echo -e "${GREEN}✅ IPv6 enabled successfully!${NC}"
    echo -e "${YELLOW}⚠️  A system reboot is recommended for full effect.${NC}"
}

# Function to disable geolocation services
disable_geolocation() {
    echo -e "${YELLOW}🔄 Disabling Geolocation services...${NC}"
    
    # Disable GNOME location services
    if command -v gsettings >/dev/null 2>&1; then
        echo -e "${CYAN}📝 Disabling GNOME location services...${NC}"
        
        # For system-wide (requires dconf)
        sudo -u "$SUDO_USER" gsettings set org.gnome.system.location enabled false 2>/dev/null || true
        sudo -u "$SUDO_USER" gsettings set org.gnome.desktop.privacy report-technical-problems false 2>/dev/null || true
        sudo -u "$SUDO_USER" gsettings set org.gnome.desktop.privacy send-software-usage-stats false 2>/dev/null || true
        
        echo -e "  ✓ GNOME location services disabled"
    fi
    
    # Disable geoclue service (if present)
    if systemctl list-unit-files | grep -q geoclue; then
        echo -e "${CYAN}🛑 Disabling geoclue service...${NC}"
        systemctl stop geoclue.service 2>/dev/null || true
        systemctl disable geoclue.service 2>/dev/null || true
        systemctl mask geoclue.service 2>/dev/null || true
        echo -e "  ✓ Geoclue service disabled and masked"
    fi
    
    # Create geoclue configuration to disable location
    if [ -d /etc/geoclue ]; then
        echo -e "${CYAN}📝 Configuring geoclue to deny location access...${NC}"
        
        mkdir -p /etc/geoclue/conf.d/
        cat > /etc/geoclue/conf.d/99-disable-location.conf << EOF
# Disable location services - Generated by XXMXLI Privacy Tool
[agent]
whitelist=

[wifi]
enable=false

[3g]
enable=false

[cdma]
enable=false

[modem-gps]
enable=false

[network-nmea]
enable=false
EOF
        echo -e "  ✓ Geoclue configuration updated"
    fi
    
    # Block common location services processes
    echo -e "${CYAN}🚫 Blocking common location services...${NC}"
    
    # Kill running location services
    pkill -f "location" 2>/dev/null || true
    pkill -f "geoclue" 2>/dev/null || true
    pkill -f "gps" 2>/dev/null || true
    
    # Block location-related network connections (optional)
    # This is commented out as it might be too aggressive
    # echo -e "${CYAN}🌐 Blocking location-related domains...${NC}"
    # Add to /etc/hosts to block location services
    # echo "127.0.0.1 location.services.mozilla.com" >> /etc/hosts
    # echo "127.0.0.1 www.googleapis.com" >> /etc/hosts
    
    echo -e "${GREEN}✅ Geolocation services disabled!${NC}"
}

# Function to enable geolocation services
enable_geolocation() {
    echo -e "${YELLOW}🔄 Enabling Geolocation services...${NC}"
    
    # Enable GNOME location services
    if command -v gsettings >/dev/null 2>&1; then
        echo -e "${CYAN}📝 Enabling GNOME location services...${NC}"
        sudo -u "$SUDO_USER" gsettings set org.gnome.system.location enabled true 2>/dev/null || true
        echo -e "  ✓ GNOME location services enabled"
    fi
    
    # Enable geoclue service
    if systemctl list-unit-files | grep -q geoclue; then
        echo -e "${CYAN}▶️ Enabling geoclue service...${NC}"
        systemctl unmask geoclue.service 2>/dev/null || true
        systemctl enable geoclue.service 2>/dev/null || true
        systemctl start geoclue.service 2>/dev/null || true
        echo -e "  ✓ Geoclue service enabled and started"
    fi
    
    # Remove geoclue restriction configuration
    rm -f /etc/geoclue/conf.d/99-disable-location.conf
    echo -e "  ✓ Geoclue restrictions removed"
    
    echo -e "${GREEN}✅ Geolocation services enabled!${NC}"
}

# Function to show current status
show_status() {
    echo -e "${GREEN}📊 Current Privacy Settings Status:${NC}"
    echo -e "${GREEN}===================================${NC}"
    
    # IPv6 Status
    echo -e "${CYAN}🌐 IPv6 Status:${NC}"
    
    local ipv6_disabled=$(cat /proc/sys/net/ipv6/conf/all/disable_ipv6 2>/dev/null || echo "unknown")
    if [ "$ipv6_disabled" = "1" ]; then
        echo -e "  Status: ${RED}DISABLED${NC}"
    elif [ "$ipv6_disabled" = "0" ]; then
        echo -e "  Status: ${GREEN}ENABLED${NC}"
    else
        echo -e "  Status: ${YELLOW}UNKNOWN${NC}"
    fi
    
    # Check individual interfaces
    for interface in $(ls /sys/class/net/); do
        if [[ $interface != "lo" ]]; then
            local if_ipv6_disabled=$(cat /proc/sys/net/ipv6/conf/$interface/disable_ipv6 2>/dev/null || echo "unknown")
            if [ "$if_ipv6_disabled" = "1" ]; then
                echo -e "  $interface: ${RED}DISABLED${NC}"
            elif [ "$if_ipv6_disabled" = "0" ]; then
                echo -e "  $interface: ${GREEN}ENABLED${NC}"
            fi
        fi
    done
    
    # Check GRUB configuration
    if grep -q "ipv6.disable=1" /etc/default/grub 2>/dev/null; then
        echo -e "  GRUB Parameter: ${RED}IPv6 DISABLED${NC}"
    else
        echo -e "  GRUB Parameter: ${GREEN}IPv6 ENABLED${NC}"
    fi
    
    echo ""
    
    # Geolocation Status
    echo -e "${CYAN}📍 Geolocation Services Status:${NC}"
    
    # Check geoclue service
    if systemctl is-active geoclue.service >/dev/null 2>&1; then
        echo -e "  Geoclue Service: ${GREEN}RUNNING${NC}"
    elif systemctl list-unit-files | grep -q geoclue; then
        if systemctl is-enabled geoclue.service >/dev/null 2>&1; then
            echo -e "  Geoclue Service: ${YELLOW}ENABLED (not running)${NC}"
        else
            echo -e "  Geoclue Service: ${RED}DISABLED${NC}"
        fi
    else
        echo -e "  Geoclue Service: ${YELLOW}NOT INSTALLED${NC}"
    fi
    
    # Check GNOME location settings
    if command -v gsettings >/dev/null 2>&1; then
        local gnome_location=$(sudo -u "$SUDO_USER" gsettings get org.gnome.system.location enabled 2>/dev/null || echo "unknown")
        if [ "$gnome_location" = "true" ]; then
            echo -e "  GNOME Location: ${GREEN}ENABLED${NC}"
        elif [ "$gnome_location" = "false" ]; then
            echo -e "  GNOME Location: ${RED}DISABLED${NC}"
        else
            echo -e "  GNOME Location: ${YELLOW}UNKNOWN/NOT AVAILABLE${NC}"
        fi
    fi
    
    echo ""
}

# Function to show menu
show_menu() {
    echo -e "${GREEN}🎯 Select an option:${NC}"
    echo -e "${GREEN}===================${NC}"
    echo -e "${WHITE}[1] Show current status${NC}"
    echo -e "${WHITE}[2] Disable IPv6 only${NC}"
    echo -e "${WHITE}[3] Disable Geolocation only${NC}"
    echo -e "${WHITE}[4] Disable both IPv6 & Geolocation${NC}"
    echo -e "${WHITE}[5] Enable IPv6 only${NC}"
    echo -e "${WHITE}[6] Enable Geolocation only${NC}"
    echo -e "${WHITE}[7] Enable both IPv6 & Geolocation${NC}"
    echo -e "${WHITE}[8] Create backup of current settings${NC}"
    echo -e "${WHITE}[9] Network troubleshooting${NC}"
    echo -e "${WHITE}[0] Exit${NC}"
    echo ""
}

# Function for network troubleshooting
network_troubleshooting() {
    echo -e "${CYAN}🔧 Network Troubleshooting:${NC}"
    echo -e "${CYAN}===========================${NC}"
    
    echo -e "${YELLOW}📡 Network Interfaces:${NC}"
    ip link show
    
    echo -e "\n${YELLOW}🌐 IPv4 Addresses:${NC}"
    ip -4 addr show
    
    echo -e "\n${YELLOW}🌐 IPv6 Addresses:${NC}"
    ip -6 addr show
    
    echo -e "\n${YELLOW}🛣️ Routing Table:${NC}"
    ip route show
    
    echo -e "\n${YELLOW}📶 DNS Configuration:${NC}"
    cat /etc/resolv.conf
    
    echo -e "\n${YELLOW}🔍 Active Network Services:${NC}"
    ss -tulpn | head -10
}

# Main script execution
show_banner

# Check for root privileges
check_root

# Detect Linux distribution
detect_distro

echo ""

# Handle command line arguments
case "${1:-menu}" in
    "disable-ipv6")
        backup_settings
        disable_ipv6
        ;;
    "disable-geo")
        backup_settings
        disable_geolocation
        ;;
    "disable-all")
        backup_settings
        echo -e "${YELLOW}🔄 Disabling both IPv6 and Geolocation...${NC}"
        disable_ipv6
        echo ""
        disable_geolocation
        echo ""
        echo -e "${GREEN}✅ Both IPv6 and Geolocation disabled!${NC}"
        ;;
    "enable-ipv6")
        enable_ipv6
        ;;
    "enable-geo")
        enable_geolocation
        ;;
    "enable-all")
        echo -e "${YELLOW}🔄 Enabling both IPv6 and Geolocation...${NC}"
        enable_ipv6
        echo ""
        enable_geolocation
        echo ""
        echo -e "${GREEN}✅ Both IPv6 and Geolocation enabled!${NC}"
        ;;
    "status")
        show_status
        ;;
    "menu"|*)
        while true; do
            show_menu
            read -p "Enter your choice (0-9): " choice
            
            case $choice in
                1)
                    show_status
                    read -p "Press Enter to continue..."
                    ;;
                2)
                    backup_settings
                    disable_ipv6
                    read -p "Press Enter to continue..."
                    ;;
                3)
                    backup_settings
                    disable_geolocation
                    read -p "Press Enter to continue..."
                    ;;
                4)
                    backup_settings
                    echo -e "${YELLOW}🔄 Disabling both IPv6 and Geolocation...${NC}"
                    disable_ipv6
                    echo ""
                    disable_geolocation
                    echo ""
                    echo -e "${GREEN}✅ Both IPv6 and Geolocation disabled!${NC}"
                    read -p "Press Enter to continue..."
                    ;;
                5)
                    enable_ipv6
                    read -p "Press Enter to continue..."
                    ;;
                6)
                    enable_geolocation
                    read -p "Press Enter to continue..."
                    ;;
                7)
                    echo -e "${YELLOW}🔄 Enabling both IPv6 and Geolocation...${NC}"
                    enable_ipv6
                    echo ""
                    enable_geolocation
                    echo ""
                    echo -e "${GREEN}✅ Both IPv6 and Geolocation enabled!${NC}"
                    read -p "Press Enter to continue..."
                    ;;
                8)
                    backup_settings
                    read -p "Press Enter to continue..."
                    ;;
                9)
                    network_troubleshooting
                    read -p "Press Enter to continue..."
                    ;;
                0)
                    echo -e "${GREEN}👋 Goodbye!${NC}"
                    exit 0
                    ;;
                *)
                    echo -e "${RED}❌ Invalid choice!${NC}"
                    read -p "Press Enter to continue..."
                    ;;
            esac
        done
        ;;
esac

echo ""
echo -e "${GREEN}📋 Script completed. Remember to use these tools responsibly!${NC}"
echo -e "${YELLOW}⚠️  Some changes may require a system restart to take full effect.${NC}"
