name: Generate tracklist.json

on:
  push:
    paths:
      - 'assets/audio/**'
      - '.github/workflows/generate-tracklist.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate tracklist.json
      run: |
        mkdir -p assets/audio
        # List supported audio files, strip path, output as JSON array
        find assets/audio -maxdepth 1 -type f \( -iname '*.mp3' -o -iname '*.flac' -o -iname '*.wav' -o -iname '*.ogg' \) \
          | sed 's|assets/audio/||' \
          | jq -R . | jq -s . > assets/audio/tracklist.json
        cat assets/audio/tracklist.json

    - name: Commit and push tracklist.json
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-generate tracklist.json"
        file_pattern: assets/audio/tracklist.json